//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIS411_Project.dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOK
    {
        public int BOOK_ID { get; set; }
        public string BOOK_TITLE { get; set; }
        public string BOOK_DESC { get; set; }
        public string BOOK_AUTHOR { get; set; }
        public Nullable<int> BOOK_EDITION { get; set; }
        public string BOOK_PUBLISHER { get; set; }
        public Nullable<decimal> ISBN10 { get; set; }
        public Nullable<decimal> ISBN13 { get; set; }
        public int CONDITION_ID { get; set; }
        public int CATEGORY_ID { get; set; }
        public int USER_ID { get; set; }
        public decimal BOOK_PRICE { get; set; }
        public byte[] CREATED_TIMESTAMP { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
        public virtual CONDITION CONDITION { get; set; }
        public virtual USER USER { get; set; }
    }
}
